name: Build and Push Docker Image

on:
  push:
    branches:
      - main  
  workflow_dispatch:

jobs:
  ci:
    if: contains(github.event.head_commit.message, 'ETL:')
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          APP: "solana-snapshot-etl"
          REGISTRY: ghcr.io/${{ github.repository_owner }}
        run: make build push
        
      - name: Clean
        run: make clean
